#!/usr/bin/env bash

function gen {
  local tmp_seed="$1"; shift
  local tmp_modules="$1"; shift
  local nm_env="$1"; shift
  local nm_app="$1"; shift
  local nm_service="$1"; shift

	jq -n \
        --argfile seed         "$tmp_seed" \
        --argfile modules      "$tmp_modules" \
        --arg     remote_bucket "$remote_bucket" \
        --arg     remote_path   "$remote_path" \
        --arg     remote_region "$remote_region" \
        --arg     region   "$region" \
        --arg     az_count     "$az_count" \
	      --arg     env_name     "$nm_env" \
        --arg     app_name     "$nm_app" \
        --arg     service_name "$nm_service" \
        --arg     want_nat     "$want_nat" \
        '$seed * $modules | .variable |= .*
            { remote_bucket: { default: "\($remote_bucket)" },
              remote_path:   { default: "\($remote_path)" },
              remote_region: { default: "\($remote_region)" },
              region:        { default: "\($region)" },
              az_count:      { default: "\($az_count)" },
              env_name:      { default: "\($env_name)" },
              app_name:      { default: "\($app_name)" },
              service_name:  { default: "\($service_name)" },
              want_nat:      { default: "\($want_nat)" },
              meh:           { default: "" }
            }'
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source _fogg "$@"
}

source sub "$BASH_SOURCE" "$@"
