#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_service="0.0.1"
  jq -n --arg fogg_service "$ver_fogg_service" '{fogg_service: $fogg_service}'
}

version "$@"
